### ISSUE TITLE
Integration in Gatsby

### ISSUE THREAD

**Issue by cgpro** [AndersDJohnson/anchorate#4]
Hi,

how to integrate anchorate in Gatsby? I added the code in gatsby-browser.js but I think thats not enough? Sorry I'm quite new to Gatsby, but I'm making good progress.

I think my layout/index.js is not complete.

Thanks

**Comment by joshuawootonn** [comment]
I am not the maintainer, but I just got it working!

1: `yarn add  anchorate`
2: gatsby-browser.js
 ```
import { anchorate } from 'anchorate'

exports.onRouteUpdate = () => {
  anchorate()
}
```
3: From _a_ tag
```
<a href="#about">More</a>
```
4: To _a_ tag
```
<a name="about" >asdf</a>
```

5: 🎉

**Comment by joshuawootonn** [comment]
Actually just put this in gatsby-browser.js 

```
exports.onRouteUpdate = (location) => {
  if (location.hash) {
    setTimeout(() => {
      document.querySelector(`${location.hash}`).scrollIntoView();
    }, 0);
  }
};
```

Don't think this package is needed

**Comment by AndersDJohnson** [comment]
@cgpro I haven't tested with the latest versions of Gatsby. Thanks @joshuawootonn for solving with this library initially. With regard to your simple solution, I'm sure it works fine for simple use cases, but this library does a bit more - it handles `name` attributes as well as `id` attributes and it does proper escaping per the spec.
